### ISSUE TITLE
Type in install details

### ISSUE THREAD

**Issue by Scaremonger** [amansx/alexa-raspberry#1]
Npm installs global into /usr/local so your service file should read:

`ExecStart=/usr/local/bin/alexa-raspberry /etc/alexa/devices.json`

Excellent bit of code, I got my existing home system running with Alexa within half hour. Very cool.

**Comment by amansx** [comment]
Thanks @Scaremonger I'll update the documentation to point out the path difference, or feel free to send a pull request. I'm also planning on updating the library to include a WebUI to add/remove commands let me know what you think.
